# Generated by Django 3.2.5 on 2021-08-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teritories', '0001_initial'),
        ('store', '0004_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teritories.territorie'),
            preserve_default=False,
        ),
    ]
