# Generated by Django 3.2.5 on 2021-07-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tegs',
            new_name='tags',
        ),
    ]
